### ISSUE TITLE
A little syntax error and header file missing

### ISSUE THREAD

**Issue by mandy1612** [ahmadshafique/CYK-Parser#1]
At line number 79 in main.cpp, there is an error. 'a.erase(remove_if(a.begin(), a.end(), isspace), a.end());' this will not work as compiler cannot determine which instance of overloaded function "isspace" is intended. You have to define the header file "cctype" & put a resolution operator(i.e. ::) before 'isspace'. After removing this bug your file main.cpp looks like this.

// some header files
#include< cctype >
using namespace std;
/*
     code same as previous till line no. 79
*/
a.erase(remove_if(a.begin(), a.end(), ::isspace), a.end());
/*
    rest of the code
*/

**Comment by ahmadshafique** [comment]
Thanks Manas. I have fixed the issue. If you found this repo useful, kindly give it a star.
